### ISSUE TITLE
Saving projects overwrites Channel 1's sample/program with last viewed channel

### ISSUE THREAD

**Issue by nyanpasu64** [osoumen/C700#15]
Currently I use the VST to map channels to instruments, not program change messages in my MIDI tracks. When I save a REAPER project with the GUI pointed to a channel greater than 1 (regardless if the GUI is open or has been closed), then when I load the project, the GUI is still pointing to the new channel, but Channel 1's active sample has been replaced by this channel's.

## System

REAPER v6.15/x64
C700 x64 VST, master (6537217d1db251e95852581e3006c703813c0fb1), compiled using VS2019 (compiler v142)

**Comment by osoumen** [comment]
@nyanpasu64 
Thank you for your report.
I've verified that this behavior only occurred in the VST version, so in the next release, Ch1 settings will be protected, as in the Audio Unit version.
