### ISSUE TITLE
Innacurate Filtering and Echo.

### ISSUE THREAD

**Issue by ZackoDum** [osoumen/C700#18]
I've been trying to do some FFVI echo from the track ''The Fierce Battle'' and they have the same exact settings, yet they don't match up.
Also the guass filtering ins't accurate.

JP:

FFVIのトラック「激闘」のehcoを再現しようとしたら、同じ設定なのに合わない。
あとSNESのフィルタリングのインは正確ではない。

https://user-images.githubusercontent.com/76856532/103449285-cf2a9300-4c84-11eb-9997-3bb1b456fb05.mp4

**Comment by osoumen** [comment]
@ZackoDum 
Can you show me the referenced setting value and the setting value entered in the C700?

**Comment by ZackoDum** [comment]
> @ZackoDum
> Can you show me the referenced setting value and the setting value entered in the C700?

![unknown-10](https://user-images.githubusercontent.com/76856532/103516141-5ecb6f80-4e46-11eb-868c-2580697abd28.png)

63, 63 Main Volume
80 Ms for delay
Echo Level was 25, 25
and 55% for feedback
and no echo FIR

**Comment by osoumen** [comment]
![スクリーンショット 2021-01-05 0 50 37](https://user-images.githubusercontent.com/7766127/103553376-b32b2980-4ef0-11eb-9b4e-bf082e31dc2b.png)

Thank you.
I entered the settings you gave me into the C700 and it looks like the figure. Doesn't the same sound sound even if it is the same as this? Note that the Feedback = 46 indicated by the SPC700 Player is a hexadecimal number.

**Comment by ZackoDum** [comment]
> ![スクリーンショット 2021-01-05 0 50 37](https://user-images.githubusercontent.com/7766127/103553376-b32b2980-4ef0-11eb-9b4e-bf082e31dc2b.png)
> 
> Thank you.
> I entered the settings you gave me into the C700 and it looks like the figure. Doesn't the same sound sound even if it is the same as this? Note that the Feedback = 46 indicated by the SPC700 Player is a hexadecimal number.

At the moment im away from my Desktop, but when i get to it I'll do some comparasions, tysm! keep developing this tool, it is such blessing!

**Comment by ZackoDum** [comment]
@osoumen Finally back at home, i made another comparasion, using the same exact settings you showed on your screencap

The Original SPC700 version somewhat feels richer than C700

https://user-images.githubusercontent.com/76856532/103579867-e604fb80-4eb7-11eb-9933-b3d8c939a2f5.mp4

**Comment by osoumen** [comment]
@ZackoDum
Did you get almost the same sound? The output sampling rate of Super Nintendo is 32000Hz, and emulation is also performed in that cycle. Therefore, in order to play it on a PC, it is necessary to convert it to a rate such as 48000KHz. Since the conversion method at that time is different between SPC700 Player and C700, the C700 may sound a little stronger in the high frequency range. However, this is because it is trying to faithfully output the digital audio generated by the emulator. This level of sound quality difference is not caused by emulation inaccuracies.

**Comment by ZackoDum** [comment]
> @ZackoDum
> Did you get almost the same sound? The output sampling rate of Super Nintendo is 32000Hz, and emulation is also performed in that cycle. Therefore, in order to play it on a PC, it is necessary to convert it to a rate such as 48000KHz. Since the conversion method at that time is different between SPC700 Player and C700, the C700 may sound a little stronger in the high frequency range. However, this is because it is trying to faithfully output the digital audio generated by the emulator. This level of sound quality difference is not caused by emulation inaccuracies.

Ooh, that might be it, i was originaly using 44100 since its FL-Studio's Default Rate, i switched to 48000, i'll do a comparasion with it, i have FL 11 & 12
![image](https://user-images.githubusercontent.com/76856532/103649579-789bae00-4f3d-11eb-9de6-a8bb02311460.png)

**Comment by osoumen** [comment]
@ZackoDum 
Whether the sampling rate of the C700 is 44100Hz or 48000Hz, there is not much difference in the output sound. The sound is output by the optimum conversion method according to each. What is the problem you want to solve?

**Comment by ZackoDum** [comment]
it actually improved, i fixed my problem here, thanks for reaching out!
